apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kompose.cmd: kompose convert -f k8s/docker-compose.yml -o k8s/base
    kompose.image-pull-secret: regcred
    kompose.service.expose: petclinic04.clarusway.us
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: vets-service
  name: vets-service
spec:
  rules:
    - host: petclinic04.clarusway.us
      http:
        paths:
          - backend:
              serviceName: vets-service
              servicePort: 8083
status:
  loadBalancer: {}
